### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by patricktokeeffe** [wsular/INL-scalar-transport#1]
Loggers store data in Pacific Standard Time (-0800) instead of local timezone, Mountain Standard Time (-0700).

**Comment by zmgao** [comment]
Changed to MST (-0700) at about 20:00 on 09/18/2020.

**Comment by patricktokeeffe** [comment]
Did you want to update timestamps in the acquired data? Or just label it and keep it separate?

**Comment by zmgao** [comment]
I would say just label it and keep it separate for the raw data, but I will update timestamps in the quality controlled data.
