### ISSUE TITLE
Missing field names in datatables

### ISSUE THREAD

**Issue by patricktokeeffe** [wsular/INL-scalar-transport#11]
## Group B

* `Anonymous1` = PAR calibration constant

## Group S

* `Anonymous1` = PAR calibration constant

**Comment by zmgao** [comment]
Fixed

**Comment by patricktokeeffe** [comment]
Fixed in 192b369c8df4eb6ca734dae03a89fb6595ad3258 and 8a14f68a5b5aceae0734954967f0b4a1455021eb by removing from data table
