### ISSUE TITLE
Unnecessary wind vector averaging

### ISSUE THREAD

**Issue by patricktokeeffe** [wsular/INL-scalar-transport#16]
Storing average & standard deviations of wind vector components doesn't add any value to the data set and consumes a lot of memory. Those columns should be removed from summary data tables. 

Instead, compute wind speed/direction/sigma/etc using the `WindVector` instruction. Note there are two options for wind direction standard deviation (sigma) - choose the more appropriate for modeling goals.

**Comment by zmgao** [comment]
These variables will be displayed on website to check the instrument status.

**Comment by patricktokeeffe** [comment]
Generally, or are these particular metrics important? Could you use `Sample()` instead? It would reduce computations and increase available storage.

**Comment by patricktokeeffe** [comment]
Items were removed from data tables. If code is reverted to include `WindVector` results, it should also incorporate the sonic azimuths so computed WD are correct.
